### ISSUE TITLE
wasp inside docker is not able to push data on Kafka

### ISSUE THREAD

**Issue by agile-lab** [agile-lab-dev/wasp#44]
If you launch wasp inside a docker and you start the metro producer, it will fail traying to send data to Kafka. 
The problem is not present if you launch wasp on the host, so not in a docker container.

**Comment by assinnata** [comment]
If this is referred about the issue we encountered in CheBanca! today I think it was about of proxy issue. It will be resolved by passing -e http_proxy=proxy.domain.xyz on every container.

**Comment by agile-lab** [comment]
Yes it is, nice to know. We have to verify this next time. Thanks
