### ISSUE TITLE
Issue with Darwin configuration

### ISSUE THREAD

**Issue by flamhero** [agile-lab-dev/wasp#7]
With this configuration...
```
  darwinConnector = "hbase"
  avroSchemaManager {
    wasp-manages-darwin-connectors-conf = false
    darwin = {
      table = "SCHEMA_REPOSITORY"
      ...
```
... Darwin uses the MockConnector.
We have to add Darwin's optional parameter `connector = "hbase"` to use the HBaseConnector.
It seems the Wasp parameter `darwinConnector = "hbase"` is not taken into account correctly.

**Comment by andrea-rockt** [comment]
the two parameters should be supplied with coherent values.

This is done here
it.agilelab.bigdata.wasp.core.utils.ConfigManager#initializeAvroSchemaManagerConfig

wasp will setup proper hbase auth for darwin only if 

darwinConnector=hbase and wasp-manages-darwin-connectors-conf=true

if this is not the case only the darwin standard configuration will be used.

Sorry if this behavior is confusing

**Comment by flamhero** [comment]
Ok, it makes sense.
However, I think the behavior has changed because we never had such an issue in the past with Darwin 1.0.13 and with `wasp-manages-darwin-connectors-conf=false`.
We just updated Darwin to 1.2.1 and started to see the issue.
Could it be related to the multi-connector feature?

Anyway, we will be careful from now on.
