### ISSUE TITLE
Kafka versions

### ISSUE THREAD

**Issue by flamhero** [agile-lab-dev/wasp#8]
Kafka version is set [here](https://github.com/agile-lab-dev/wasp/blob/a1dc468cfbcabf3639d6f015d99fbc4f91a5ab8f/project/CDP717Versions.scala#L48).
Kafka-clients version is set [here](https://github.com/agile-lab-dev/wasp/blob/a1dc468cfbcabf3639d6f015d99fbc4f91a5ab8f/project/CDP717Dependencies.scala#L312).

The versions are different.
Is it normal?

**Comment by andrea-rockt** [comment]
kafka client versions comes from an actual analysis of parcel dependencies.

Kafka clients are usually compatible with every version of kafka server and rarely have breaking changes (usually coming from a change of the kafka wire protocol, something that actually rarely happens)

I'll check if the correct  dependency is actually that (i'm almost sure it is) but even if mismatched should be fine to use

**Comment by flamhero** [comment]
Ok, that's fine!
